/* Pickleball Signup v1.0 — local-storage version, no fake data. Ready for GitHub Pages. */
const STORE='pickleballSignupV1';
const DEFAULT_COORD='pickleball123';
const $=sel=>document.querySelector(sel);
const app=$('#app');
let state=load();
let session=JSON.parse(localStorage.getItem('pickleballSessionV1')||'null');
function load(){const raw=localStorage.getItem(STORE); if(raw) return JSON.parse(raw); return {users:{}, coordPass:DEFAULT_COORD, locations:['DinkHouse','Liberty Park','Cerritos Courts'], events:[]};}
function save(){localStorage.setItem(STORE,JSON.stringify(state));}
function setSession(s){session=s;localStorage.setItem('pickleballSessionV1',JSON.stringify(s));render();}
function logout(){localStorage.removeItem('pickleballSessionV1');session=null;render();}
function uid(){return Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function fmtDate(d){return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'});}
function today(){return new Date().toISOString().slice(0,10)}
function timeLabel(t){if(!t)return ''; let [h,m]=t.split(':').map(Number), am=h>=12?'PM':'AM'; h=h%12||12; return `${h}:${String(m).padStart(2,'0')} ${am}`}
function render(){ if(!session) return renderLogin(); return renderApp(session.view||'player');}
function renderLogin(){app.innerHTML=`<div class="wrap login"><div style="width:100%"><div class="hero"><h1>🏓 Pickleball Signup</h1><p>Login or create your player account.</p></div><div class="card"><h2>Player Login</h2><label>Email</label><input id="email" type="email" placeholder="you@email.com"><label>Password</label><div class="passwordBox"><input id="pass" type="password" placeholder="Password"><button class="secondary" onclick="togglePass('pass',this)">Show</button></div><label>Your Name</label><input id="name" placeholder="Needed only when creating account"><div class="row" style="margin-top:14px"><button onclick="playerLogin()">Login</button><button class="secondary" onclick="createPlayer()">Create Account</button><button class="ghost" onclick="forgotPassword()">Forgot Password</button></div><p class="small">First time? Enter email, password, name, then Create Account.</p></div><div class="card"><h2>Coordinator Login</h2><label>Coordinator Password</label><div class="passwordBox"><input id="coordPass" type="password" placeholder="Coordinator password"><button class="secondary" onclick="togglePass('coordPass',this)">Show</button></div><button style="margin-top:12px;width:100%" onclick="coordLogin()">Open Coordinator</button><p class="small">Default password: pickleball123. Change it in Coordinator Settings.</p></div></div></div>`}
function togglePass(id,btn){const el=document.getElementById(id);el.type=el.type==='password'?'text':'password';btn.textContent=el.type==='password'?'Show':'Hide'}
function createPlayer(){const email=$('#email').value.trim().toLowerCase(), pass=$('#pass').value, name=$('#name').value.trim(); if(!email||!pass||!name)return alert('Enter email, password, and name.'); if(state.users[email])return alert('Account already exists. Please login.'); state.users[email]={email,pass,name,children:[]}; save(); setSession({role:'player',email,view:'player'});}
function playerLogin(){const email=$('#email').value.trim().toLowerCase(), pass=$('#pass').value; if(!state.users[email]||state.users[email].pass!==pass)return alert('Wrong email or password.'); setSession({role:'player',email,view:'player'});}
function forgotPassword(){const email=prompt('Enter your account email:'); if(!email)return; const key=email.trim().toLowerCase(); if(!state.users[key])return alert('No account found with that email.'); const p=prompt('Demo reset: enter a new password. In the cloud version this will send an email reset link.'); if(!p)return; if(p.length<4)return alert('Use at least 4 characters.'); state.users[key].pass=p; save(); alert('Password reset for demo. You can login with your new password.');}
function coordLogin(){if($('#coordPass').value!==state.coordPass)return alert('Wrong coordinator password.'); setSession({role:'coordinator',view:'coordinator'});}
function nav(view){session.view=view;setSession(session)}
function renderApp(view){const role=session.role; app.innerHTML=`<div class="wrap"><div class="hero"><h1>🏓 Pickleball Signup</h1><p>${role==='coordinator'?'Coordinator dashboard':'Welcome, '+esc(state.users[session.email]?.name||'Player')}</p></div><div class="tabs"><button class="tab ${view==='player'?'active':''}" onclick="nav('player')">Player</button><button class="tab ${view==='calendar'?'active':''}" onclick="nav('calendar')">Calendar</button>${role==='player'?`<button class="tab ${view==='profile'?'active':''}" onclick="nav('profile')">Profile</button>`:''}${role==='coordinator'?`<button class="tab ${view==='coordinator'?'active':''}" onclick="nav('coordinator')">Coordinator</button>`:''}<button class="tab" onclick="logout()">Logout</button></div><main id="main"></main><div class="footer">GitHub Pages v1.0 • Local storage now • Firebase-ready later</div></div>`; if(view==='calendar')renderCalendar(); else if(view==='profile'&&role==='player')renderProfile(); else if(view==='coordinator'&&role==='coordinator')renderCoordinator(); else renderPlayer();}
function eventCounts(ev){return {playing:ev.signups.filter(s=>s.status==='playing').length, interested:ev.signups.filter(s=>s.status==='interested').length,total:ev.signups.length}}
function eventStatus(ev){const c=eventCounts(ev); if(ev.closed)return {label:'CLOSED',cls:'red'}; if(ev.full || (Number(ev.max||0)>0 && c.playing>=Number(ev.max)))return {label:'FULLY BOOKED',cls:'red'}; if(ev.booked)return {label:'BOOKED',cls:'green'}; return {label:'Waiting',cls:'yellow'};}
function canSignup(ev){const st=eventStatus(ev); return st.label!=='CLOSED' && st.label!=='FULLY BOOKED' && !isClosed(ev);}
function isClosed(ev){if(ev.cutoff==='open')return false; const hrs=Number(ev.cutoff||0); if(!ev.date||!ev.start)return false; return new Date()>=new Date(`${ev.date}T${ev.start}:00`)-hrs*3600000;}

function renderProfile(){
 const user=state.users[session.email];
 $('#main').innerHTML=`<div class="card"><h2>Edit Profile</h2><label>Name</label><input id="profileName" value="${esc(user.name)}"><label>Email / Login ID</label><input id="profileEmail" type="email" value="${esc(user.email)}"><p class="small">Changing email also changes your login ID and ownership of your signups.</p><label>New Password</label><div class="passwordBox"><input id="profilePass" type="password" placeholder="Leave blank to keep current password"><button class="secondary" onclick="togglePass('profilePass',this)">Show</button></div><button style="margin-top:12px" onclick="saveProfile()">Save Profile</button></div><div class="card"><h2>Family Members</h2><div class="list">${user.children.map((n,i)=>`<div class="person"><b>${esc(n)}</b><span><button class="secondary" onclick="editChild(${i})">Edit</button> <button class="danger" onclick="removeChild(${i})">Delete</button></span></div>`).join('')||'<p class="small">No children added yet.</p>'}</div><div class="row"><input id="profileChild" placeholder="Add child name"><button onclick="addChildFromProfile()">Add Child</button></div></div>`
}
function saveProfile(){
 const old=session.email, user=state.users[old];
 const name=$('#profileName').value.trim(), newEmail=$('#profileEmail').value.trim().toLowerCase(), pass=$('#profilePass').value;
 if(!name||!newEmail)return alert('Name and email are required.');
 if(newEmail!==old && state.users[newEmail])return alert('That email is already used.');
 user.name=name; user.email=newEmail; if(pass)user.pass=pass;
 if(newEmail!==old){state.users[newEmail]=user; delete state.users[old]; state.events.forEach(e=>e.signups.forEach(s=>{if(s.owner===old)s.owner=newEmail;})); session.email=newEmail;}
 save(); setSession(session); alert('Profile updated.');
}
function addChildFromProfile(){const n=$('#profileChild').value.trim(); if(!n)return; state.users[session.email].children.push(n); save(); renderProfile();}
function editChild(i){const user=state.users[session.email]; const old=user.children[i]; const n=prompt('Child name:',old); if(!n)return; user.children[i]=n; state.events.forEach(e=>e.signups.forEach(s=>{if(s.owner===session.email && s.name===old)s.name=n;})); save(); renderProfile();}
function removeChild(i){const user=state.users[session.email]; const old=user.children[i]; if(!confirm('Remove this child from your profile? Existing signups for this child will also be removed.'))return; user.children.splice(i,1); state.events.forEach(e=>e.signups=e.signups.filter(s=>!(s.owner===session.email && s.name===old))); save(); renderProfile();}

function renderPlayer(){const user=state.users[session.email]; const events=[...state.events].sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)); $('#main').innerHTML=`<div class="card"><h2>My Family</h2><div class="list">${[user.name,...user.children].map(n=>`<div class="person"><b>${esc(n)}</b></div>`).join('')||''}</div><div class="row"><input id="childName" placeholder="Add child name"><button onclick="addChild()">Add Child</button></div></div>${events.length?events.map(eventCardPlayer).join(''):`<div class="card"><h2>No play dates yet</h2><p class="small">Waiting for coordinator to create the first event.</p></div>`}`}
function addChild(){const n=$('#childName').value.trim();if(!n)return;state.users[session.email].children.push(n);save();renderPlayer()}
function eventCardPlayer(ev){
 const c=eventCounts(ev), closed=!canSignup(ev), mine=ev.signups.filter(s=>s.owner===session.email), family=[state.users[session.email].name,...state.users[session.email].children], st=eventStatus(ev);
 return `<div class="card"><div class="eventTop"><div><div class="big">${fmtDate(ev.date)}</div><p>📍 <b>${esc(ev.location)}</b><br>🕒 ${timeLabel(ev.start)} - ${timeLabel(ev.end)}</p></div><div>${c.playing>=6?'<span class="badge red">6+ Ready</span>':''} <span class="badge '+st.cls+'">'+st.label+'</span></div></div>${ev.booked?`<div class="notice"><b>Booking Details</b><br>${esc(ev.details||'Court booked. Details coming soon.')}</div>`:`<div class="notice warn"><b>Waiting for court reservation.</b><br>Minimum 6 playing players before booking court.</div>`}${ev.feeOn?`<div class="card" style="box-shadow:none"><b>💵 Court Fee:</b> $${esc(ev.fee||'')}<br><b>Payment:</b> ${esc(ev.payment||'')}</div>`:''}<h3>Sign up / Update my family</h3>${closed?`<p class="badge red">${st.label==='FULLY BOOKED'?'Fully booked':'Signup closed'}</p>`:family.map(n=>{const ex=mine.find(s=>s.name===n);return `<div class="person"><b>${esc(n)}</b><span>${ex?esc(ex.status):'Not signed up'}</span><div><button class="secondary" onclick="upsertSignup('${ev.id}','${esc(n)}','interested')">Interested</button> <button class="success" onclick="upsertSignup('${ev.id}','${esc(n)}','playing')">Playing</button></div></div>`}).join('')}<h3>Who’s Coming</h3><div class="list">${ev.signups.length?ev.signups.map(s=>`<div class="person"><span>${s.status==='playing'?'✅':'👍'} <b>${esc(s.name)}</b> <span class="small">${esc(s.status)}</span></span></div>`).join(''):'<p class="small">No signups yet.</p>'}</div></div>`}
function upsertSignup(eid,name,status){const ev=state.events.find(e=>e.id===eid);let s=ev.signups.find(x=>x.owner===session.email&&x.name===name); if(!canSignup(ev) && !s)return alert('Signup is closed or fully booked.'); if(status==='playing' && !s && eventStatus(ev).label==='FULLY BOOKED')return alert('This event is fully booked.'); if(s)s.status=status; else ev.signups.push({id:uid(),owner:session.email,name,status,checked:false}); save();renderPlayer();}
function renderCalendar(){const grouped={};state.events.forEach(e=>{(grouped[e.date]??=[]).push(e)});$('#main').innerHTML=`<div class="card"><h2>Calendar</h2>${Object.keys(grouped).sort().length?Object.keys(grouped).sort().map(d=>`<div class="card" style="box-shadow:none"><div class="big">${fmtDate(d)}</div>${grouped[d].map(e=>{const c=eventCounts(e);return `<p>${c.playing>=6?'🔴':'⚪'} ${timeLabel(e.start)} ${esc(e.location)} — ${c.playing} playing, ${c.interested} interested • ${eventStatus(e).label}</p>`}).join('')}</div>`).join(''):'<p class="small">No events yet.</p>'}</div>`}
function renderCoordinator(){const events=[...state.events].sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start));$('#main').innerHTML=`<div class="dash"><div class="stat"><span>Events</span><b>${state.events.length}</b></div><div class="stat"><span>Locations</span><b>${state.locations.length}</b></div><div class="stat"><span>Players</span><b>${Object.keys(state.users).length}</b></div></div><div class="card"><h2>Create / Edit Event</h2><input id="editId" type="hidden"><div class="row"><div><label>Date</label><input id="date" type="date" value="${today()}"></div><div><label>Start</label><input id="start" type="time" value="19:00"></div><div><label>End</label><input id="end" type="time" value="21:00"></div></div><label>Location</label><select id="location">${state.locations.map(l=>`<option>${esc(l)}</option>`).join('')}</select><div class="row"><div><label>Signup Cutoff</label><select id="cutoff"><option value="open">Keep open until event</option><option value="1">Close 1 hour before</option><option value="2">Close 2 hours before</option><option value="4">Close 4 hours before</option></select></div><div><label>Max players</label><input id="max" type="number" value="12"></div></div><div class="toggleLine"><input id="booked" type="checkbox"><b>Court Booked?</b></div><div class="toggleLine"><input id="closed" type="checkbox"><b>Close Signups?</b></div><div class="toggleLine"><input id="full" type="checkbox"><b>Mark Fully Booked?</b></div><label>Booking Details</label><textarea id="details" placeholder="Court #, parking, arrival time, what to bring..."></textarea><div class="toggleLine"><input id="feeOn" type="checkbox"><b>Collect court fee?</b></div><div class="row"><input id="fee" placeholder="Fee e.g. 5"><input id="payment" placeholder="Venmo/Zelle/Cash info"></div><div class="row" style="margin-top:12px"><button onclick="saveEvent()">Save Event</button><button class="secondary" onclick="clearEventForm()">Clear</button></div></div><div class="card"><h2>Events</h2>${events.length?events.map(eventCardCoord).join(''):'<p class="small">No events yet.</p>'}</div><div class="card"><h2>Manage Locations</h2><div class="list">${state.locations.map((l,i)=>`<div class="person"><b>${esc(l)}</b><span><button class="secondary" onclick="renameLocation(${i})">Edit</button> <button class="danger" onclick="deleteLocation(${i})">Delete</button></span></div>`).join('')}</div><div class="row"><input id="newLocation" placeholder="New location"><button onclick="addLocation()">Add Location</button></div></div><div class="card"><h2>Coordinator Settings</h2><label>Change Password</label><div class="passwordBox"><input id="newCoordPass" type="password" placeholder="New coordinator password"><button class="secondary" onclick="togglePass('newCoordPass',this)">Show</button></div><button style="margin-top:10px" onclick="changeCoordPass()">Save Password</button></div>`}
function saveEvent(){const id=$('#editId').value;const data={date:$('#date').value,start:$('#start').value,end:$('#end').value,location:$('#location').value,cutoff:$('#cutoff').value,max:$('#max').value,booked:$('#booked').checked,closed:$('#closed').checked,full:$('#full').checked,details:$('#details').value,feeOn:$('#feeOn').checked,fee:$('#fee').value,payment:$('#payment').value}; if(!data.date||!data.start||!data.end||!data.location)return alert('Complete date, time, and location.'); if(id){Object.assign(state.events.find(e=>e.id===id),data)}else{state.events.push({id:uid(),...data,signups:[]})} save();renderCoordinator();}
function eventCardCoord(ev){const c=eventCounts(ev);return `<div class="card" style="box-shadow:none"><div class="eventTop"><div><div class="big">${fmtDate(ev.date)} — ${esc(ev.location)}</div><p>${timeLabel(ev.start)} - ${timeLabel(ev.end)} • ${c.playing} playing • ${c.interested} interested</p></div><div><span class="badge ${eventStatus(ev).cls}">${eventStatus(ev).label}</span></div></div><div class="row"><button class="secondary" onclick="editEvent('${ev.id}')">Edit</button><button class="danger" onclick="deleteEvent('${ev.id}')">Delete</button><button onclick="exportCsv('${ev.id}')">Export CSV</button></div><h3>Players</h3>${ev.signups.length?ev.signups.map(s=>`<div class="person"><span>${s.status==='playing'?'✅':'👍'} <b>${esc(s.name)}</b> <span class="small">${esc(s.owner)}</span></span><span><button class="secondary" onclick="toggleCheck('${ev.id}','${s.id}')">${s.checked?'Checked In':'Check In'}</button> <button class="danger" onclick="removeSignup('${ev.id}','${s.id}')">Remove</button></span></div>`).join(''):'<p class="small">No signups yet.</p>'}</div>`}
function editEvent(id){const e=state.events.find(x=>x.id===id);['date','start','end','location','cutoff','max','details','fee','payment'].forEach(k=>{if($('#'+k))$('#'+k).value=e[k]||''});$('#editId').value=e.id;$('#booked').checked=!!e.booked;$('#closed').checked=!!e.closed;$('#full').checked=!!e.full;$('#feeOn').checked=!!e.feeOn;window.scrollTo({top:0,behavior:'smooth'});}
function clearEventForm(){renderCoordinator()}
function deleteEvent(id){if(confirm('Delete this event?')){state.events=state.events.filter(e=>e.id!==id);save();renderCoordinator();}}
function removeSignup(eid,sid){const e=state.events.find(x=>x.id===eid);e.signups=e.signups.filter(s=>s.id!==sid);save();renderCoordinator();}
function toggleCheck(eid,sid){const s=state.events.find(e=>e.id===eid).signups.find(s=>s.id===sid);s.checked=!s.checked;save();renderCoordinator();}
function addLocation(){const v=$('#newLocation').value.trim();if(!v)return;state.locations.push(v);save();renderCoordinator();}
function renameLocation(i){const v=prompt('New location name:',state.locations[i]);if(!v)return;const old=state.locations[i];state.locations[i]=v;state.events.forEach(e=>{if(e.location===old)e.location=v});save();renderCoordinator();}
function deleteLocation(i){if(state.locations.length<=1)return alert('Keep at least one location.');if(confirm('Delete location?')){state.locations.splice(i,1);save();renderCoordinator();}}
function changeCoordPass(){const p=$('#newCoordPass').value.trim();if(p.length<4)return alert('Use at least 4 characters.');state.coordPass=p;save();alert('Coordinator password updated.');}
function exportCsv(id){const e=state.events.find(x=>x.id===id);let csv='Name,Status,Email,Checked In\n'+e.signups.map(s=>`"${s.name}","${s.status}","${s.owner}","${s.checked?'yes':'no'}"`).join('\n');const blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pickleball-${e.date}-${e.location}.csv`;a.click();}
render();
